#!/usr/bin/env bash
# Wire harness-skills into a consuming project for each detected agent.
# Idempotent and re-runnable. Run after `git submodule update --remote`.
set -euo pipefail

SKILLS_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# PROJECT_ROOT = the superproject that embeds this submodule. Overridable via HARNESS_PROJECT_ROOT
# (tests project into a temp dir); else the superproject, else two levels up.
PROJECT_ROOT="${HARNESS_PROJECT_ROOT:-}"
if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT="$(git -C "$SKILLS_SRC" rev-parse --show-superproject-working-tree 2>/dev/null || true)"
  [ -n "$PROJECT_ROOT" ] || PROJECT_ROOT="$(cd "$SKILLS_SRC/../.." && pwd)"
fi
mkdir -p "$PROJECT_ROOT"
# Physical path (-P): relative symlinks must resolve correctly even when the root is under a
# symlinked path (e.g. macOS /tmp -> /private/tmp).
PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd -P)"
# Antigravity global config dir (registry at <dir>/config/skills.json). Overridable so tests never
# pollute the real home.
GEMINI_CONFIG_DIR="${GEMINI_CONFIG_DIR:-$HOME/.gemini}"

echo "==> harness-skills install"
echo "    source : $SKILLS_SRC"
echo "    project: $PROJECT_ROOT"

# Ensure the nested caveman submodule is present.
if [ ! -e "$SKILLS_SRC/vendor/caveman/.git" ] && [ ! -f "$SKILLS_SRC/vendor/caveman/SKILL.md" ]; then
  echo "==> pulling nested submodules (vendor/caveman) ..."
  git -C "$SKILLS_SRC" submodule update --init --recursive 2>/dev/null || \
    echo "    WARN: could not init vendor/caveman (run: git submodule update --init --recursive)"
fi

# Relative path from PROJECT_ROOT to the submodule (for portable symlinks).
rel_src() { python3 -c "import os,sys;print(os.path.relpath(sys.argv[1],sys.argv[2]))" "$1" "$2" 2>/dev/null || echo "$1"; }

# --- Claude Code: symlink .claude/skills -> skills-src/skills ---
wire_claude_code() {
  local link="$PROJECT_ROOT/.claude/skills"
  mkdir -p "$PROJECT_ROOT/.claude"
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    echo "==> Claude Code: $link exists and is NOT a symlink — leaving it (merge skills manually)"
    return 0
  fi
  rm -f "$link"
  ln -s "$(rel_src "$SKILLS_SRC/skills" "$PROJECT_ROOT/.claude")" "$link"
  echo "==> Claude Code: symlinked .claude/skills -> skills-src/skills"
}

# --- Antigravity: generate .agents/workflows/harness-<name>.md adapters for each workflow-* ---
# Antigravity uses .agents/ (plural) as its default config dir; .agent/ is legacy. We standardize
# on .agents/ and migrate any adapters left in a legacy .agent/workflows from earlier installs.
wire_antigravity() {
  local out="$PROJECT_ROOT/.agents/workflows"
  mkdir -p "$out"
  # Migrate: drop adapters this installer previously generated under legacy .agent/workflows.
  local legacy="$PROJECT_ROOT/.agent/workflows"
  if [ -d "$legacy" ]; then
    rm -f "$legacy"/harness-workflow-*.md
    rmdir "$legacy" 2>/dev/null && rmdir "$PROJECT_ROOT/.agent" 2>/dev/null || true
  fi
  local count=0
  for d in "$SKILLS_SRC"/skills/workflow-*/; do
    [ -d "$d" ] || continue
    local name desc
    name="$(basename "$d")"
    desc="$(grep -m1 -iE '^description:' "$d/SKILL.md" 2>/dev/null | sed -E 's/^[Dd]escription:[[:space:]]*//')"
    {
      echo "---"
      echo "name: harness-$name"
      echo "description: ${desc:-harness $name}"
      echo "---"
      echo ""
      echo "Run the harness skill **$name**. Read and follow its canonical definition:"
      echo ""
      echo "    .harness/skills-src/skills/$name/SKILL.md"
      echo ""
      echo "(Generated adapter — do not edit; regenerated by install.sh.)"
    } > "$out/harness-$name.md"
    count=$((count + 1))
  done
  echo "==> Antigravity: generated $count .agents/workflows/harness-* adapters"
}

# --- Codex: symlink .agents/skills -> skills-src/skills (Codex resolves symlinked skill folders) ---
# Default location is .agents/skills (shared dir with Antigravity). Antigravity does NOT source skills
# by walking this symlink (it uses skills.json, see wire_antigravity_skills), so the symlink serves
# Codex only. Escape hatch: if a given Antigravity build hard-errors on the symlink's presence in
# .agents/, set HARNESS_CODEX_SKILLS_LINK=<abs path> to relocate it (e.g. "$PROJECT_ROOT/.codex/skills").
wire_codex() {
  local link="${HARNESS_CODEX_SKILLS_LINK:-$PROJECT_ROOT/.agents/skills}"
  local linkdir; linkdir="$(dirname "$link")"
  mkdir -p "$linkdir"
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    echo "==> Codex: $link exists and is NOT a symlink — leaving it (merge skills manually)"
    return 0
  fi
  rm -f "$link"
  ln -s "$(rel_src "$SKILLS_SRC/skills" "$linkdir")" "$link"
  echo "==> Codex: symlinked ${link#$PROJECT_ROOT/} -> skills-src/skills"
}

# --- Antigravity: generate skills.json registry pointing at the canonical skills dir (ABS path) ---
# Antigravity resolves symlinks to absolute paths and its file-walker may skip symlinks, so a
# registry — not the .agents/skills symlink — is the robust source of truth for it. We write both a
# workspace registry (.agents/skills.json, project-scoped + authoritative) and the global one
# (<GEMINI_CONFIG_DIR>/config/skills.json, merge-safe). Schema: {"entries":[{"path":"<abs dir>"}]}.
wire_antigravity_skills() {
  local abs="$SKILLS_SRC/skills"
  local ws="$PROJECT_ROOT/.agents/skills.json"
  local gl="$GEMINI_CONFIG_DIR/config/skills.json"
  mkdir -p "$PROJECT_ROOT/.agents" "$GEMINI_CONFIG_DIR/config"
  # Workspace registry: project-scoped, single entry (always our canonical dir).
  python3 - "$abs" "$ws" <<'PY'
import json, sys
abs_path, out = sys.argv[1], sys.argv[2]
json.dump({"entries": [{"path": abs_path}]}, open(out, "w"), indent=2)
open(out, "a").write("\n")
PY
  # Global registry: merge-safe — preserve existing entries, add ours, dedupe by path.
  python3 - "$abs" "$gl" <<'PY'
import json, os, sys
abs_path, out = sys.argv[1], sys.argv[2]
data = {}
if os.path.exists(out):
    try:
        data = json.load(open(out)) or {}
    except Exception:
        data = {}
entries = data.get("entries")
if not isinstance(entries, list):
    entries = []
seen, merged = set(), []
for e in entries + [{"path": abs_path}]:
    p = e.get("path") if isinstance(e, dict) else None
    if not p or p in seen:
        continue
    seen.add(p)
    merged.append({"path": p} if list(e.keys()) == ["path"] else e)
data["entries"] = merged
json.dump(data, open(out, "w"), indent=2)
open(out, "a").write("\n")
PY
  echo "==> Antigravity: wrote skills.json registry (workspace .agents/skills.json + ${gl})"
}

# --- Hooks: merge config-templates into per-agent settings (templates land in F12) ---
wire_hooks() {
  local tmpl="$SKILLS_SRC/config-templates/claude.settings.json"
  local settings="$PROJECT_ROOT/.claude/settings.json"
  if [ ! -f "$tmpl" ]; then
    echo "==> Hooks: no config-templates yet (provided by F12) — skipping"
    return 0
  fi
  if command -v jq >/dev/null 2>&1; then
    mkdir -p "$PROJECT_ROOT/.claude"
    if [ -f "$settings" ]; then
      jq -s '.[0] * .[1]' "$settings" "$tmpl" > "$settings.tmp" && mv "$settings.tmp" "$settings"
      echo "==> Hooks: merged config-templates/claude.settings.json into .claude/settings.json"
    else
      cp "$tmpl" "$settings"
      echo "==> Hooks: installed .claude/settings.json from template"
    fi
  else
    echo "==> Hooks: jq not found — merge $tmpl into $settings manually"
  fi
}

# --- Antigravity hooks: install config-templates/antigravity.hooks.json into .agents/hooks.json ---
# Antigravity reads workspace hooks from .agents/hooks.json (the new default dir;
# .agent/ is legacy). Our gates run through hooks/antigravity-hook.sh, which bridges
# Antigravity's stdin-JSON / stdout-decision contract to the canonical gate scripts.
wire_antigravity_hooks() {
  local tmpl="$SKILLS_SRC/config-templates/antigravity.hooks.json"
  local hooks="$PROJECT_ROOT/.agents/hooks.json"
  [ -f "$tmpl" ] || { echo "==> Antigravity hooks: no template — skipping"; return 0; }
  chmod +x "$SKILLS_SRC/hooks/antigravity-hook.sh" 2>/dev/null || true
  mkdir -p "$PROJECT_ROOT/.agents"
  if command -v jq >/dev/null 2>&1; then
    if [ -f "$hooks" ]; then
      # Shallow-merge top-level named blocks: our "harness-gates" key is set/replaced,
      # any user-defined blocks are preserved.
      jq -s '.[0] * .[1]' "$hooks" "$tmpl" > "$hooks.tmp" && mv "$hooks.tmp" "$hooks"
      echo "==> Antigravity hooks: merged into .agents/hooks.json"
    else
      cp "$tmpl" "$hooks"
      echo "==> Antigravity hooks: installed .agents/hooks.json from template"
    fi
  else
    echo "==> Antigravity hooks: jq not found — merge $tmpl into $hooks manually"
  fi
}

wire_claude_code
wire_antigravity
wire_antigravity_skills
wire_codex
wire_hooks
wire_antigravity_hooks

echo "==> done. Skills + workflows + hooks wired for Claude Code / Antigravity / Codex."
