#!/usr/bin/env bash
# Wire harness-skills into a consuming project for each detected agent.
# Idempotent and re-runnable. Run after `git submodule update --remote`.
set -euo pipefail

SKILLS_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# PROJECT_ROOT = the superproject that embeds this submodule (fallback: two levels up).
PROJECT_ROOT="$(git -C "$SKILLS_SRC" rev-parse --show-superproject-working-tree 2>/dev/null || true)"
[ -n "$PROJECT_ROOT" ] || PROJECT_ROOT="$(cd "$SKILLS_SRC/../.." && pwd)"

echo "==> harness-skills install"
echo "    source : $SKILLS_SRC"
echo "    project: $PROJECT_ROOT"

# Ensure the nested caveman submodule is present.
if [ ! -e "$SKILLS_SRC/vendor/caveman/.git" ] && [ ! -f "$SKILLS_SRC/vendor/caveman/SKILL.md" ]; then
  echo "==> pulling nested submodules (vendor/caveman) ..."
  git -C "$SKILLS_SRC" submodule update --init --recursive 2>/dev/null || \
    echo "    WARN: could not init vendor/caveman (run: git submodule update --init --recursive)"
fi

# Relative path from PROJECT_ROOT to the submodule (for portable symlinks).
rel_src() { python3 -c "import os,sys;print(os.path.relpath(sys.argv[1],sys.argv[2]))" "$1" "$2" 2>/dev/null || echo "$1"; }

# --- Claude Code: symlink .claude/skills -> skills-src/skills ---
wire_claude_code() {
  local link="$PROJECT_ROOT/.claude/skills"
  mkdir -p "$PROJECT_ROOT/.claude"
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    echo "==> Claude Code: $link exists and is NOT a symlink — leaving it (merge skills manually)"
    return 0
  fi
  rm -f "$link"
  ln -s "$(rel_src "$SKILLS_SRC/skills" "$PROJECT_ROOT/.claude")" "$link"
  echo "==> Claude Code: symlinked .claude/skills -> skills-src/skills"
}

# --- Antigravity: generate .agent/workflows/harness-<name>.md adapters for each workflow-* ---
wire_antigravity() {
  local out="$PROJECT_ROOT/.agent/workflows"
  mkdir -p "$out"
  local count=0
  for d in "$SKILLS_SRC"/skills/workflow-*/; do
    [ -d "$d" ] || continue
    local name desc
    name="$(basename "$d")"
    desc="$(grep -m1 -iE '^description:' "$d/SKILL.md" 2>/dev/null | sed -E 's/^[Dd]escription:[[:space:]]*//')"
    {
      echo "---"
      echo "name: harness-$name"
      echo "description: ${desc:-harness $name}"
      echo "---"
      echo ""
      echo "Run the harness skill **$name**. Read and follow its canonical definition:"
      echo ""
      echo "    .harness/skills-src/skills/$name/SKILL.md"
      echo ""
      echo "(Generated adapter — do not edit; regenerated by install.sh.)"
    } > "$out/harness-$name.md"
    count=$((count + 1))
  done
  echo "==> Antigravity: generated $count .agent/workflows/harness-* adapters"
}

# --- Codex: path-based, no projection needed ---
wire_codex() {
  echo "==> Codex: path-based — reads .harness/skills-src/skills/<name>/SKILL.md directly (no projection)"
}

# --- Hooks: merge config-templates into per-agent settings (templates land in F12) ---
wire_hooks() {
  local tmpl="$SKILLS_SRC/config-templates/claude.settings.json"
  local settings="$PROJECT_ROOT/.claude/settings.json"
  if [ ! -f "$tmpl" ]; then
    echo "==> Hooks: no config-templates yet (provided by F12) — skipping"
    return 0
  fi
  if command -v jq >/dev/null 2>&1; then
    mkdir -p "$PROJECT_ROOT/.claude"
    if [ -f "$settings" ]; then
      jq -s '.[0] * .[1]' "$settings" "$tmpl" > "$settings.tmp" && mv "$settings.tmp" "$settings"
      echo "==> Hooks: merged config-templates/claude.settings.json into .claude/settings.json"
    else
      cp "$tmpl" "$settings"
      echo "==> Hooks: installed .claude/settings.json from template"
    fi
  else
    echo "==> Hooks: jq not found — merge $tmpl into $settings manually"
  fi
}

# --- Antigravity hooks: install config-templates/antigravity.hooks.json into .agents/hooks.json ---
# Antigravity reads workspace hooks from .agents/hooks.json (the new default dir;
# .agent/ is legacy). Our gates run through hooks/antigravity-hook.sh, which bridges
# Antigravity's stdin-JSON / stdout-decision contract to the canonical gate scripts.
wire_antigravity_hooks() {
  local tmpl="$SKILLS_SRC/config-templates/antigravity.hooks.json"
  local hooks="$PROJECT_ROOT/.agents/hooks.json"
  [ -f "$tmpl" ] || { echo "==> Antigravity hooks: no template — skipping"; return 0; }
  chmod +x "$SKILLS_SRC/hooks/antigravity-hook.sh" 2>/dev/null || true
  mkdir -p "$PROJECT_ROOT/.agents"
  if command -v jq >/dev/null 2>&1; then
    if [ -f "$hooks" ]; then
      # Shallow-merge top-level named blocks: our "harness-gates" key is set/replaced,
      # any user-defined blocks are preserved.
      jq -s '.[0] * .[1]' "$hooks" "$tmpl" > "$hooks.tmp" && mv "$hooks.tmp" "$hooks"
      echo "==> Antigravity hooks: merged into .agents/hooks.json"
    else
      cp "$tmpl" "$hooks"
      echo "==> Antigravity hooks: installed .agents/hooks.json from template"
    fi
  else
    echo "==> Antigravity hooks: jq not found — merge $tmpl into $hooks manually"
  fi
}

wire_claude_code
wire_antigravity
wire_codex
wire_hooks
wire_antigravity_hooks

echo "==> done. Skills + workflows + hooks wired for Claude Code / Antigravity / Codex."
