#!/usr/bin/env bash
# Generate the Codex implicit-invocation policy (openai.yaml) from skill frontmatter `metadata.tier`.
#
# Weak-model footgun: Codex/Antigravity auto-load skills by description semantic-match, so surfacing
# all ~83 skills lets a weak model pull craft/expert/component skills out-of-band, bypassing the
# spine + gates. Policy: ONLY `tier: entry` skills may be implicitly auto-selected; every other skill
# (judgment / mechanical / no tier) is `allow_implicit_invocation: false` — reachable by explicit
# name only. Default-off is fail-safe: a skill is implicit ONLY if it explicitly declares tier:entry.
#
# Single source of truth = the same frontmatter F46/F47 read. Output is deterministic (sorted).
#
# Usage:
#   gen-implicit-policy.sh            # print the openai.yaml to stdout
#   gen-implicit-policy.sh --write <path>   # write it to <path>
# Exit 0 on success; non-zero on an unknown tier value (fail loud).
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

exec python3 - "$ROOT" "$@" <<'PY'
import os, re, sys

root = sys.argv[1]
args = sys.argv[2:]
out_path = None
if args:
    if args[0] == "--write" and len(args) > 1:
        out_path = args[1]
    else:
        sys.stderr.write(f"gen-implicit-policy: unknown argument '{args[0]}'\n")
        sys.exit(2)

skills_dir = os.path.join(root, "skills")
VALID_TIERS = {"entry", "judgment", "mechanical"}

def read_tier(path):
    """Return metadata.tier for a SKILL.md, or '' if none. Tiny frontmatter reader (no pyyaml)."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        return ""
    end = text.find("\n---", 3)
    if end == -1:
        return ""
    in_meta = False
    for line in text[3:end].splitlines():
        if re.match(r"^metadata:\s*$", line):
            in_meta = True
            continue
        if in_meta:
            if line and not line.startswith(" "):
                in_meta = False
                continue
            m = re.match(r"^\s{2}tier:\s*(\S+)", line)
            if m:
                return m.group(1).strip().strip('"').strip("'")
    return ""

rows = []
errors = []
for name in sorted(os.listdir(skills_dir)):
    sp = os.path.join(skills_dir, name, "SKILL.md")
    if not os.path.isfile(sp):
        continue
    tier = read_tier(sp)
    if tier and tier not in VALID_TIERS:
        errors.append(f"{name}: unknown tier '{tier}' (want one of {sorted(VALID_TIERS)})")
        continue
    rows.append((name, tier == "entry"))

if errors:
    sys.stderr.write("gen-implicit-policy: frontmatter errors:\n  " + "\n  ".join(errors) + "\n")
    sys.exit(2)

lines = [
    "# GENERATED by scripts/gen-implicit-policy.sh from skill frontmatter metadata.tier — do not edit.",
    "# Policy: ONLY tier:entry skills may be implicitly auto-selected; all others are explicit-name only.",
    "# This protects the spine — a weak model cannot pull craft/expert/component skills out-of-band.",
    "skills:",
]
for name, implicit in rows:
    lines.append(f"  {name}:")
    lines.append(f"    allow_implicit_invocation: {'true' if implicit else 'false'}")
content = "\n".join(lines) + "\n"

if out_path:
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    n_entry = sum(1 for _, i in rows if i)
    sys.stderr.write(f"gen-implicit-policy: wrote {out_path} ({len(rows)} skills, {n_entry} entry/implicit-on)\n")
else:
    sys.stdout.write(content)
PY
